# Generated by Django 4.1 on 2022-08-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conntent',
            new_name='content',
        ),
    ]
