# Generated by Django 4.1 on 2022-08-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='autors.autor')),
            ],
        ),
    ]
