# Generated by Django 4.1 on 2022-08-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="relase_date",
            new_name="release_date",
        ),
    ]
